### ISSUE TITLE
Exception in exception.log magento

### ISSUE THREAD

**Issue by slimshadyplace** [vovayatsyuk/magento-alsoviewed#10]
Hello,

great work you did with this module! But I got an error in the exception log:

```
Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes, query was: INSERT INTO `yavva_alsoviewed_relation` (`product_id`,`related_product_id`,`weight`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), ..[this goes on for like 800 rules].. (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) ON DUPLICATE KEY UPDATE `weight` = weight + VALUES(weight)' in /home/admin/domains/domain.nl/public_html/lib/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /home/admin/domains/domain.nl/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/admin/domains/domain.nl/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/admin/domains/domain.nl/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/admin/domains/domain.nl/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ya...', Array)
#4 /home/admin/domains/domain.nl/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ya...', Array)
#5 /home/admin/domains/domain.nl/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(1934): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ya...', Array)
#6 /home/admin/domains/domain.nl/public_html/app/code/community/Yavva/Alsoviewed/Model/Resource/Relation.php(43): Varien_Db_Adapter_Pdo_Mysql->insertOnDuplicate('yavva_alsoviewe...', Array, Array)
#7 /home/admin/domains/domain.nl/public_html/app/code/community/Yavva/Alsoviewed/Model/Observer.php(44): Yavva_Alsoviewed_Model_Resource_Relation->updateRelations(Array)
#8 [internal function]: Yavva_Alsoviewed_Model_Observer->processLog(Object(Mage_Cron_Model_Schedule))
#9 /home/admin/domains/domain.nl/public_html/app/code/core/Mage/Cron/Model/Observer.php(325): call_user_func_array(Array, Array)
#10 /home/admin/domains/domain.nl/public_html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule)
```

Do you know what causes this or is this a bug?

Best regards,
Sebastiaan

**Comment by vovayatsyuk** [comment]
Hi,

Looks like that many relations where generated and query size was bigger than `max_allowed_packet` size.

There are two solutions for that:
1. Increase `max_allowed_packet` setting: http://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size
2. Split the query into smaller parts. I think I should do that to prevent super large queries. 
 The easiest way is to split the large data array into chunks and run the process with smaller parts.

**Possible solution:**
Replace the [Observer.php#L44-45](https://github.com/vovayatsyuk/magento-alsoviewed/blob/master/app/code/community/Yavva/Alsoviewed/Model/Observer.php#L44-L45) with:

```php
foreach (array_chunk($data, 200) as $chunk) {
    Mage::getResourceModel('alsoviewed/relation')->updateRelations($chunk);
}
$log->clean();
```

**Comment by vovayatsyuk** [comment]
https://github.com/vovayatsyuk/magento-alsoviewed/commit/b94c0f65c90921957843e1145dca0a7ffc444a4a

New config will be available in the next release.
