### ISSUE TITLE
doesnt works with easytabs extension.

### ISSUE THREAD

**Issue by sarrafj** [vovayatsyuk/magento-alsoviewed#13]
i am using easytabs with custom theme shoe_stores.

i have also placed the following code in local.xml file.. but nothing is chaged.
```
 <catalog_product_view>
      <reference name="product.info.additional">
          <action method="unsetChild"><name>alsoviewed.collateral.wrapper</name></action>
      </reference>
      <reference name="product.info.tabs">
          <action method="addTab" translate="title" module="alsoviewed" ifconfig="alsoviewed/content/enabled">
              <alias>alsoviewed.collateral.wrapper</alias>
              <title><![CDATA[You may also like]]></title>
          </action>
      </reference>
  </catalog_product_view>
```
i can only see the products listed above the easytabs instead of showing inside the tab.

**Comment by vovayatsyuk** [comment]
Please check the following:

1. Do you have a valid local.xml file?
 ```xml
<?xml version="1.0"?>
<layout version="0.1.0">
    your code should be here
</layout>
```

2. Turn off the cache at `System > Cache Management`
3. What Magento version do you use?

**Comment by sarrafj** [comment]
i am using magento 1.8.1

in my local.xml file when i try to put xml version and layout version. i am getting an error that says 
```
Warning: Missing argument 3 for Mage_Catalog_Block_Product_View_Tabs::addTab()  in /public_html/alpha4/app/code/core/Mage/Catalog/Block/Product/View/Tabs.php on line 46

#0 /public_html/alpha4/app/code/core/Mage/Catalog/Block/Product/View/Tabs.php(46): mageCoreErrorHandler(2, 'Missing argumen...', '/home3/ab89271/...', 46, Array)
#1 [internal function]: Mage_Catalog_Block_Product_View_Tabs->addTab('alsoviewed.coll...', 'You may also li...')
#2 /public_html/alpha4/app/code/core/Mage/Core/Model/Layout.php(348): call_user_func_array(Array, Array)
#3 /public_html/alpha4/app/code/core/Mage/Core/Model/Layout.php(214): Mage_Core_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#4 /public_html/alpha4/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#5 /public_html/alpha4/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /public_html/alpha4/app/code/core/Mage/Cms/Helper/Page.php(113): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /public_html/alpha4/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'no-route')
#8 /public_html/alpha4/app/code/core/Mage/Cms/controllers/IndexController.php(75): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'no-route')
#9 /public_html/alpha4/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->noRouteAction()
#10 /public_html/alpha4/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#11 /public_html/alpha4/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /public_html/alpha4/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /public_html/alpha4/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /public_html/alpha4/index.php(92): Mage::run('', 'store')
#15 {main}
```

so i tried checking whats on /app/code/core/Mage/Catalog/Block/Product/View/Tabs.php on line 46
and it says 
```
function addTab($alias, $title, $block, $template)
    {

        if (!$title || !$block || !$template) {
            return false;
        }

        $this->_tabs[] = array(
            'alias' => $alias,
            'title' => $title
        );

        $this->setChild($alias,
            $this->getLayout()->createBlock($block, $alias)
                ->setTemplate($template)
            );
    }

    function getTabs()
    {
        return $this->_tabs;
    }
}
```
i am getting no clue what to do. again if i remove the xml and layout version and put my xml code directly into the local.xml file .. the above error is gone.

**Comment by vovayatsyuk** [comment]
It's ok that error is showing up. This means that xml code starts working.

You should update EasyTabs to [2.3.3](https://github.com/tmhub/easytabs/releases/tag/2.3.3)

**Comment by sarrafj** [comment]
sorry but the latest version of easytab is not working. my custom theme came preloaded with the easytab. and whenever i try to update it by replacing the files .. the module stops working

**Comment by vovayatsyuk** [comment]
Sorry, but old EasyTabs module does not support adding tabs from layout.

If you are using EasyTabs 2.2, than you can add `Html tab` from backend interface
and use Also Viewed Products widget inside content field:

![easytabs_html_content](https://cloud.githubusercontent.com/assets/306080/8034681/a9502946-0df2-11e5-8c36-dfefc5d3b07c.png)
