### ISSUE TITLE
error message from exception.log

### ISSUE THREAD

**Issue by cewolf2002** [vovayatsyuk/magento-alsoviewed#27]
Hi, I got a lot of this error message in recent.
Could you let me know how to solve it?

```
2017-04-13T03:45:02+00:00 ERR (3): 
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`yavva_alsoviewed_relation`, CONSTRAINT `FK_YAVVA_ALSOVIEWED_RELATION_RELATED_PRD_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`related_product_id`) REFERENCES `catalog_product_entity` (`en)' in /usr/share/nginx/html/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/nginx/html/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/nginx/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/nginx/html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /usr/share/nginx/html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /usr/share/nginx/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ya...', Array)
#5 /usr/share/nginx/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ya...', Array)
#6 /usr/share/nginx/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(2036): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ya...', Array)
#7 /usr/share/nginx/html/app/code/community/Yavva/Alsoviewed/Model/Resource/Relation.php(43): Varien_Db_Adapter_Pdo_Mysql->insertOnDuplicate('yavva_alsoviewe...', Array, Array)
#8 /usr/share/nginx/html/app/code/community/Yavva/Alsoviewed/Model/Observer.php(52): Yavva_Alsoviewed_Model_Resource_Relation->updateRelations(Array)
#9 [internal function]: Yavva_Alsoviewed_Model_Observer->processLog(Object(Mage_Cron_Model_Schedule))
#10 /usr/share/nginx/html/app/code/core/Mage/Cron/Model/Observer.php(326): call_user_func_array(Array, Array)
#11 /usr/share/nginx/html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#12 /usr/share/nginx/html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#13 /usr/share/nginx/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#14 /usr/share/nginx/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#15 /usr/share/nginx/html/cron.php(78): Mage::dispatchEvent('default')
#16 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`yavva_alsoviewed_relation`, CONSTRAINT `FK_YAVVA_ALSOVIEWED_RELATION_RELATED_PRD_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`related_product_id`) REFERENCES `catalog_product_entity` (`en), query was: INSERT INTO `yavva_alsoviewed_relation` (`product_id`,`related_product_id`,`weight`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) ON DUPLICATE KEY UPDATE `weight` = weight + VALUES(weight)' in /usr/share/nginx/html/lib/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /usr/share/nginx/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/nginx/html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /usr/share/nginx/html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /usr/share/nginx/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ya...', Array)
#4 /usr/share/nginx/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ya...', Array)
#5 /usr/share/nginx/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(2036): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ya...', Array)
#6 /usr/share/nginx/html/app/code/community/Yavva/Alsoviewed/Model/Resource/Relation.php(43): Varien_Db_Adapter_Pdo_Mysql->insertOnDuplicate('yavva_alsoviewe...', Array, Array)
#7 /usr/share/nginx/html/app/code/community/Yavva/Alsoviewed/Model/Observer.php(52): Yavva_Alsoviewed_Model_Resource_Relation->updateRelations(Array)
#8 [internal function]: Yavva_Alsoviewed_Model_Observer->processLog(Object(Mage_Cron_Model_Schedule))
#9 /usr/share/nginx/html/app/code/core/Mage/Cron/Model/Observer.php(326): call_user_func_array(Array, Array)
#10 /usr/share/nginx/html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#11 /usr/share/nginx/html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#12 /usr/share/nginx/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#13 /usr/share/nginx/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#14 /usr/share/nginx/html/cron.php(78): Mage::dispatchEvent('default')
#15 {main}
```

**Comment by vovayatsyuk** [comment]
Hi, I think it was [fixed](https://github.com/vovayatsyuk/magento-alsoviewed/commit/bcd27f63acc3a375031470a308da5bda6e8678bf) in latest 1.3.1 release.

What version do you use?

**Comment by cewolf2002** [comment]
I'm using 1.3.0 now, will try to update to 1.3.1 today.

**Comment by cewolf2002** [comment]
Issue solved after updating.
Thanks for your help.
